### ISSUE TITLE
`sequence` info is missing in schema returned from `get_schema`

### ISSUE THREAD

**Issue by psergee** [tarantool/ddl#122]
How to reproduce:
Actual index info:
```
box.space._migrations.index
---
- 0: &0
    parts:
    - type: unsigned
      is_nullable: false
      fieldno: 1
    sequence_id: 1
    id: 0
    space_id: 512
    unique: true
    hint: true
    type: TREE
    name: primary
    sequence_fieldno: 1
  primary: *0
```

DDL schema:
```
ddl.get_schema().spaces._migrations.indexes
---
- - type: TREE
    parts:
    - path: id
      is_nullable: false
      type: unsigned
    name: primary
    unique: true
```

Sequence is missing. So, after applying cluster-wide schema from `ddl.get-schema` index sequence configuration is lost.
