### ISSUE TITLE
Allow custom fields in space:format

### ISSUE THREAD

**Issue by dsamirov** [tarantool/ddl#36]
I can use additional fields in space:format with some metadata. For example:
```
localhost:3302> box.space.my_space:format({{name = 'a', type = 'string' }, {name = 'b', type = 'string', comment = 'awesome comment'}})
localhost:3302> box.space.my_space:format()
---
- [{'name': 'a', 'type': 'string'}, {'type': 'string', 'comment': 'awesome comment',
    'name': 'b'}]
...
```

But when I try to add this field in Cartridge DDL:
```
spaces:
  my_space:
    format:
      - is_nullable: false
        type: unsigned
        name: bucket_id
        comment: blabla
```
I see the error: `spaces["my_space"].format["bucket_id"]: redundant key "comment"`
